parameters:

  header:
    ## Header information is used for logging. It is good practice to give your simulations explicit names
    title: Isotropic Elastic simulation # name for your simulation
    # A detailed description for your simulation
    description: |
      Material systems : Elastic domain (1)
      Interfaces : None
      Sources : Force source (1)
      Boundary conditions : Neumann BCs on all edges

  simulation-setup:
    ## quadrature setup
    quadrature:
      quadrature-type: GLL4

    ## Solver setup
    solver:
      time-marching:
        time-scheme:
          type: Newmark
          dt: 1.0e-4
          nstep: 10000

    simulation-mode:
      forward:
        writer:
          # wavefield:
          #   directory: "/home/lsawade/SPECFEMPP/benchmarks/build/release-cuda/dim2/homogeneous-cosserat/OUTPUT_FILES/results"
          #   time_interval: 400
          #   format: "HDF5"
          seismogram:
            format: "ascii"
            directory: "/home/lsawade/SPECFEMPP/benchmarks/build/release-cuda/dim2/homogeneous-cosserat/OUTPUT_FILES/results"
          display:
            format: PNG
            directory: "/home/lsawade/SPECFEMPP/benchmarks/build/release-cuda/dim2/homogeneous-cosserat/OUTPUT_FILES/display"
            field: rotation
            simulation-field: forward
            time-interval: 100

  receivers:
    stations: "/home/lsawade/SPECFEMPP/benchmarks/build/release-cuda/dim2/homogeneous-cosserat/OUTPUT_FILES/STATIONS"
    angle: 0.0
    seismogram-type:
      - displacement
      - rotation
    nstep_between_samples: 1

  ## Runtime setup
  run-setup:
    number-of-processors: 1
    number-of-runs: 1

  ## databases
  databases:
    mesh-database: "/home/lsawade/SPECFEMPP/benchmarks/build/release-cuda/dim2/homogeneous-cosserat/OUTPUT_FILES/database.bin"

  ## sources
  sources: "/home/lsawade/SPECFEMPP/benchmarks/build/release-cuda/dim2/homogeneous-cosserat/source.yaml"
